# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Service

# Model Form Field configuration
form: $/davox/company/models/service/fields.yaml

# Model Class name
modelClass: Davox\Company\Models\Service

# Default redirect location
defaultRedirect: davox/company/services

# Create page
create:
    title: backend::lang.form.create_title
    redirect: davox/company/services/update/:id
    redirectClose: davox/company/services

# Update page
update:
    title: backend::lang.form.update_title
    redirect: davox/company/services
    redirectClose: davox/company/services

# Preview page
preview:
    title: backend::lang.form.preview_title
